FROM debian:bookworm-slim

# Install only original specified packages
RUN apt-get update && \
    apt-get install -y \
        curl \
        ffmpeg \
        git \
        locales \
        nano \
        python3-pip \
        screen \
        ssh \
        unzip \
        wget && \
    rm -rf /var/lib/apt/lists/*

# Configure SSH (password + key)
RUN mkdir -p /run/sshd /root/.ssh && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'root:choco' | chpasswd

# Install ngrok with proper config
ARG NGROK_TOKEN
ARG SSH_PUBLIC_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFshKeW/SRrfepjUPfA8LfZRg3sqX4rKhrSXB5w6K1Li Generated By Termius"
RUN wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip && \
    unzip ngrok.zip && \
    echo "version: 2" > /ngrok.yml && \
    echo "authtoken: ${NGROK_TOKEN}" >> /ngrok.yml && \
    echo "region: ap" >> /ngrok.yml && \
    chmod +x ngrok && \
    echo "${SSH_PUBLIC_KEY}" >> /root/.ssh/authorized_keys && \
    chmod 600 /root/.ssh/authorized_keys

# Startup script with fixed ngrok config and proper URL display
RUN echo "#!/bin/bash" > /start.sh && \
    echo "./ngrok tcp 22 --config=ngrok.yml --log=stdout &" >> /start.sh && \
    echo "/usr/sbin/sshd -D &" >> /start.sh && \
    echo "python3 -m http.server 10000 --bind 0.0.0.0 &" >> /start.sh && \
    echo "sleep 5 # Wait for ngrok" >> /start.sh && \
    echo "NGROK_URL=\$(curl -s http://localhost:4040/api/tunnels | python3 -c \"import sys,json; print(json.load(sys.stdin)['tunnels'][0]['public_url']\")" >> /start.sh && \
    echo "echo 'SSH Access:'" >> /start.sh && \
    echo "echo '- Connect to: '\$NGROK_URL" >> /start.sh && \
    echo "echo '- Password: choco (or use your Termius key)'" >> /start.sh && \
    echo "while true; do sleep 1000; done" >> /start.sh && \
    chmod +x /start.sh

EXPOSE 10000
CMD ["/start.sh"]
